lightcone_corrections.pdf:	lightcone_corrections.tex references.bib
	pdflatex lightcone_corrections.tex
	#bibtex lightcone_corrections
	#pdflatex lightcone_corrections.tex
	#pdflatex lightcone_corrections.tex

clean:
	\rm -f *.log *.out *.pdf *.blg *.aux lightcone_corrections.bbl

