#!/bin/bash -l

# skip HYDRO_FIDUCIAL

for run in HYDRO_WEAK_AGN HYDRO_STRONG_AGN HYDRO_STRONGER_AGN HYDRO_STRONGEST_AGN HYDRO_STRONG_SUPERNOVA HYDRO_STRONGER_AGN_STRONG_SUPERNOVA HYDRO_JETS_published HYDRO_STRONG_JETS_published HYDRO_PLANCK HYDRO_PLANCK_LARGE_NU_VARY HYDRO_PLANCK_LARGE_NU_FIXED HYDRO_PLANCK_LARGER_NU_FIXED HYDRO_LOW_SIGMA8 HYDRO_PLANCK_DCDM_12 HYDRO_PLANCK_DCDM_24 HYDRO_LOW_SIGMA8_STRONGEST_AGN HYDRO_ADIABATIC ; do

    if [ -e "/cosma8/data/dp004/flamingo/Runs/L1000N1800/${run}/hbt_lightcone_halos" ] ; then
        sbatch -J "${run}" --array=0-1%1 ./reindex_halos_L1000N1800.sh
    else
        echo Missing: ${run}
    fi
done
